### ISSUE TITLE
Individual records incorrectly marked as "housed" 

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#14] opened 2019-12-05 15:47 UTC
I went in to the "unhoused" records in the 1930 census and found that some people in a building are marked as "unhoused" but not all.  If you go into one of the unhoused people and then go to one of their family members you will see no building info entered yet the system did not recognize the others as "unhoused."

**Comment by dfurber** [comment] 2020-07-18 21:05
If this is still an issue please give me some individual records that display the problem so I know where to start :)

**Comment by EveSnyder** [comment] 2020-11-23 17:28
I'm having some volunteers go through all the buildings block by block, ED by ED.  Once they get done we might have some specific examples for you but I don't at the moment.

**Comment by EveSnyder** [comment] 2020-11-25 17:00
Found one!!! 1940 census ED 24 list of unhoused people gives me Florence Teeter, but not her husband Herbert Teeter.  I checked his record and he is also not attached to a building.

**Comment by dfurber** [comment] 2021-01-30 21:27
Closing as duplicate of the Vincent Crouch issue. The problem with E Spencer St is that there isn't one. It is Spencer St. I think I found a bug whereby when entering a new record, it ignores the prefix, which allowed Flo get to matched to 126 Spencer St, but once saved, it minds the prefix, which caused Herbie to have a empty list.

**Closed as completed by dfurber** 2021-01-30 21:27 UTC
